name: 'payload-auth-Services'

services:
  postgres:
    image: 'postgis/postgis:17-3.5'
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data q 

volumes:
  pgdata: